### ISSUE TITLE
what is "E_TASK_STATE_BLOCKED" means?

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros#114]
```
pros::Task *shootTask = nullptr;
void autonomous()
{
    if (shoot != nullptr && shootTask == nullptr) 
        shootTask = new pros::Task((pros::task_fn_t)taskShoot, nullptr, TASK_PRIORITY_DEFAULT, TASK_STACK_DEPTH_DEFAULT, "task_shoot");
    userauto();
    shootTask->remove();
    delete shootTask;
    shootTask = nullptr;
}
```
```
void disabled()
{
    if (shootTask != nullptr)
    {
        std::cout << shootTask->get_name() << " " << shootTask->get_state() << std::endl;
        if (shootTask->get_state() != 4) 
         {
            shootTask->remove();
           delete shootTask;
           shootTask = nullptr;
         }
    }
    shoot->resetAllSensors(); 
}
```
When I finished the automatic game ahead of time and did not` delete shootTask`
.
The program enters `void disabled ()`
 `shootTask->get_state()` return 2  `E_TASK_STATE_BLOCKED`
Then the plane crashed.
I don't need to `shootTask->remove() & delete shootTask` manually? like `shard_ptr`?
if i use` shared_ptr` It will not crash.
But the global smart pointer is not really released.

**Comment by edjubuh** [comment]
`E_TASK_STATE_BLOCKED` typically means that the task is blocked trying to do something like acquire a mutex.

---

Issues opened on GitHub are treated as tasks that need to be performed. We close issues that are questions because there is no task to perform. For questions about programming with PROS, there are several options:
- [PROS Docs](https://pros.cs.purdue.edu/tutorials)
- [VEX Forum](https://www.vexforum.com/c/edr-technical-support/pros-support)
- [PROS Development Slack Team](https://join.slack.com/t/pros-development/shared_invite/enQtMzIyNzA2MTU2MDgwLWNlNTk3ZjA3ZWZmM2Q0YzI3NDZkZWE0MzU4ODdkM2U5MzhjZDY4M2RjNzBiZWYzODk0MTdkYzBiMzJjMWUyYmI)
- The #coding channel on the [Unofficial VEX Discord Server](https://discord.gg/32VrqVt)

The VEX Forum, the Slack team, and Discord all have very helpful community members that are happy to help with questions about using PROS.
