### ISSUE TITLE
pros::c::adi_digital_write() Makes Program Hang

### ISSUE THREAD

**Issue by TaranMayer** [purduesigbots/pros#357]
#### Expected Behavior:
1) Program starts
2) Screen displays "Hello PROS User!" for one second
3) ADI port 4 is set to "HIGH" and the screen reads "HIGH"
4) 1-second delay
5) ADI port 5 is set to "LOW" and the screen reads "LOW"
6) 1-second delay
7) Repeat 3-6 forever

#### Actual Behavior:
1) Program starts
2) Screen displays "Hello PROS User!" for one second
3) ADI port 4 is set to "HIGH" and the screen reads "HIGH"
4) Nothing further happens, program hangs seemingly forever

#### Steps to reproduce:
```cpp
void initialize() {
	pros::lcd::initialize();
	pros::lcd::set_text(1, "Hello PROS User!");
	pros::lcd::register_btn1_cb(on_center_button);
}
void opcontrol() {
	pros::delay(1000);
	while (true) {

		pros::c::adi_digital_write(4, HIGH);
		pros::lcd::set_text(1, "HIGH");

		pros::delay(1000);


		pros::c::adi_digital_write(4, LOW);
		pros::lcd::set_text(1, "LOW");

		pros::delay(1000);

	}
}
```

#### System information:
Platform: V5 V1.1.1 (b25)
Kernel Version: 3.5.4 

#### Additional Information
Using `pros::ADIDigitalOut` and `set_value()` works fine, it is specifically the C API that isn't working. 

Charles (sazrocks) replicated the error on his own V5. 

#### Screenshots/Output Dumps/Stack Traces

Nothing displays in the terminal when the hang happens.

**Comment by lachlan2k** [comment]
The functionality isn't entirely broken. The API requires a call to `pros::c::adi_pin_mode(4, OUTPUT);` before `digital_write`s can be performed. If you add this, the example program **should** work as intended.

However, the reported behavior is still buggy. Per the [docs](https://pros.cs.purdue.edu/v5/api/c/adi.html#adi-digital-write), `adi_digital_write` should return `PROS_ERR` and set `errno` to `EADDRINUSE` -- it should not hang indefinitely.

I would say though, the documentation is maybe a bit lacking. The example code for `adi_digital_write` in the docs should include a call to `adi_pin_mode`. When the documentation states "... a pin configured as a digital output.", it could be worth mentioning something like "a pin configured as a digital output with a call to adi_pin_mode" or similar.

The bug is probably somewhere around here:
https://github.com/purduesigbots/pros/blob/c2dafd2d9d007f8d22e09b7de3a9d38ad88575c4/src/devices/vdml_ext_adi.c#L209-L215

https://github.com/purduesigbots/pros/blob/c2dafd2d9d007f8d22e09b7de3a9d38ad88575c4/src/devices/vdml_ext_adi.c#L65-L70

It looks to me that `validate_type` doesn't release the mutex on failure. This is why the first call seems to work correctly, but the second call hangs -- presumably deadlocked on taking the mutex.

I suspect if a call to `port_give_mutex` is added, this will probably fix the issue.

`return_port` shows how this should be done:

https://github.com/purduesigbots/pros/blob/c2dafd2d9d007f8d22e09b7de3a9d38ad88575c4/include/vdml/vdml.h#L109-L112
