### ISSUE TITLE
Backmerge Changes from PROS 3.7.3 into 4

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros#478]
We need to get all changes from update 3.7.3 into 4, this shouldn't take long.

Also, we really shouldn't be using "4" as the version number on develop-pros-4, it should be 3.x to indicate what version we have it updated to and then update it to 4 on release like all our other feature/develop branches.

**Comment by Richard-Stump** [comment]
These are the two things that were changed in 3.7.3 that need to be brought over to PROS 4

🐛 Fix global pros::Rotation objects creating a data abort exception.
🐛 Fix bug with LED non-extended constructor.

The size() and [] operator for motor groups doesn't need moved over since we are rewriting them.

**Comment by Richard-Stump** [comment]
The following features from 3.7.2 also need ported over:


✨ Added support for addressable LED strips by @omegaStag in https://github.com/purduesigbots/pros/issues/424
✨ Added timekeeping functionality through the clock_gettime() and clock_settime() support, enabling standard the standard libraries chrono and time.h by @Richard-Stump in https://github.com/purduesigbots/pros/pull/127
Bugfixes:
🐛 Add ext_ to missing CPP functions for adi C++ by @WillXuCodes in https://github.com/purduesigbots/pros/pull/438

**Comment by Richard-Stump** [comment]
https://github.com/purduesigbots/pros/pull/459
